# Generated by Django 5.0.7 on 2025-05-21 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermenu',
            options={'ordering': ['creation_date']},
        ),
    ]
