GET http://localhost:3000/menu

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Another User",
    "emailAddress": "test@anything.com",
    "password": "Password123!"
}
###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Another User",
    "emailAddress": "test@anything.com",
    "password": ""
}

###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "emailAddress": "test@anything.com",
    "password": "Password123!"
}

###
GET http://localhost:3000/users/5c2ddf6e-4661-4de1-a1ea-c6ca714a3883