POST    http://localhost:8000/token/
Content-Type: application/json

{
  "username": "admin",
  "password": "Jimmifred!"
}

###
POST http://localhost:8000/token/refresh/
Content-Type: application/json

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0NzkzMjEyMiwiaWF0IjoxNzQ3ODQ1NzIyLCJqdGkiOiJmM2E3ZDU2NTA0ZGI0MDgyYjEyNDkzNDY0MWVhN2Y2YiIsInVzZXJfaWQiOjF9.xdfcixkZEbSxpQgga2M6RZbNtrSTXtWovztqgzRlyBg"
}