# Generated by Django 5.2.1 on 2025-05-19 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientQuantity',
            new_name='RecipeIngredientAmount',
        ),
    ]
