# Generated by Django 5.2.1 on 2025-05-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_ingredientquantity_recipeingredientamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='video',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
