# Generated by Django 5.2.1 on 2025-05-19 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_image_alter_recipe_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeIngredientAmount',
            new_name='RecipeIngredient',
        ),
    ]
